# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  related_issues: true
  related_prs: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
  tools:
    biome:
      enabled: true
chat:
  auto_reply: true
